import = [
    "~/.config/alacritty/themes/tokyo-night-storm.toml"
]

[font]
normal = { family = "DejaVu Sans Mono" }

[shell]
program = "/bin/fish"
args = ["-l", "-c", "tmux"]

[window]
dimensions = { columns = 150, lines = 50 }
