vim.opt.spell = true
vim.opt.spelllang = { "en" }
vim.opt.expandtab = true
vim.opt.shiftwidth = 2
vim.opt.tabstop = 2
vim.opt.updatetime = 750
vim.opt.shada = "!,'32,<50,s10,h"
vim.opt.pumheight = 16
vim.opt.colorcolumn = "120"
vim.opt.guicursor = "i:block-blinkwait50-blinkon200-blinkoff150"
vim.opt.undofile = true
vim.opt.signcolumn = "yes"
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.clipboard = "unnamedplus"
vim.opt.scrolloff = 10

vim.wo.relativenumber = true
vim.wo.number = true
