ALACRITTY_VERSION=0.13.2
DELTA_VERSION=0.17.0
FZF_VERSION=0.54.3
MOLD_VERSION=2.33.0
NVIM_VERSION=0.10.1
PYRIGHT_VERSION=1.1.375
TMUX_VERSION=3.4

ALACRITTY_REPO=alacritty/alacritty
DELTA_REPO=dandavison/delta
FZF_REPO=junegunn/fzf
MOLD_REPO=rui314/mold
NVIM_REPO=neovim/neovim
PYRIGHT_REPO=microsoft/pyright
TMUX_REPO=tmux/tmux
