ALACRITTY_VERSION=0.15.0
DELTA_VERSION=0.18.2
FD_VERSION=10.2.0
FZF_VERSION=0.58.0
GH_VERSION=2.65.0
JQ_VERSION=jq-1.7.1
MOLD_VERSION=2.36.0
NVIM_VERSION=0.10.4
PYRIGHT_VERSION=1.1.393
RUFF_VERSION=0.0.60
TMUX_VERSION=3.5a
UV_VERSION=0.5.25

ALACRITTY_REPO=alacritty/alacritty
DELTA_REPO=dandavison/delta
FD_REPO=sharkdp/fd
FZF_REPO=junegunn/fzf
GH_REPO=cli/cli
JQ_REPO=jqlang/jq
MOLD_REPO=rui314/mold
NVIM_REPO=neovim/neovim
PYRIGHT_REPO=microsoft/pyright
RUFF_REPO=astral-sh/ruff-lsp
TMUX_REPO=tmux/tmux
UV_REPO=astral-sh/uv

VENV_PATH=~/.cache/devenv/venv
